"use client";

import { Printer } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";

import { useSpaceReport } from "@/hooks/useSpaces";
import { formatDateTime, formatPercent } from "@/lib/format";
import { findingStatusDisplay, projectStatusDisplay } from "@/lib/status";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { ErrorState } from "@/components/ui/ErrorState";
import { StatusBadge } from "@/components/ui/Badge";
import { SkeletonCard } from "@/components/ui/Skeleton";

/**
 * The rolled-up client report — one place that answers "how is this client
 * doing across every one of their projects," instead of clicking into each
 * project's own report one at a time. Every figure is a direct aggregation
 * of already-verified per-project data (see routers/spaces.py's
 * get_space_report), same "never LLM-generated" guarantee as the
 * per-project report.
 */
export default function SpaceReportPage() {
  const params = useParams<{ spaceId: string }>();
  const { data: report, isLoading, error, refetch } = useSpaceReport(params.spaceId);

  if (error) return <ErrorState error={error} onRetry={() => refetch()} />;
  if (isLoading || !report) return <SkeletonCard />;

  const conflictCount = report.findings_by_status.find((s) => s.status === "CONFLICTING")?.count ?? 0;

  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "var(--space-4)", marginBottom: "var(--space-5)" }}>
        <div>
          <h2 style={{ margin: 0, fontSize: "var(--font-size-xl)", fontWeight: "var(--font-weight-semibold)" }}>
            {report.space.name} — Client Report
          </h2>
          <p style={{ margin: "var(--space-1) 0 0", fontSize: "var(--font-size-sm)", color: "var(--text-tertiary)" }}>
            Generated {formatDateTime(report.generated_at)} · Rolled up across {report.project_count} project
            {report.project_count === 1 ? "" : "s"} · every figure below is computed directly from live data, never
            generated by the AI.
          </p>
        </div>
        <Button variant="secondary" onClick={() => window.print()}>
          <Printer size={15} aria-hidden /> Export PDF
        </Button>
      </div>

      <div id="report-print-root" style={{ display: "grid", gap: "var(--space-5)" }}>
        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Executive summary</h2>} />
          <CardBody>
            <div className="metric-grid" style={{ gridTemplateColumns: "repeat(4, minmax(0,1fr))" }}>
              <SummaryMetric label="Projects" value={report.project_count} />
              <SummaryMetric label="Tasks delivered" value={`${report.requirements_delivered} / ${report.total_requirements}`} />
              <SummaryMetric label="Findings" value={report.total_findings} />
              <SummaryMetric label="Conflicts found" value={conflictCount} warn={conflictCount > 0} />
            </div>
            {report.total_findings === 0 ? (
              <div className="uncertainty-callout" style={{ marginTop: "var(--space-4)" }}>
                No findings have been recorded yet across this client's projects.
              </div>
            ) : conflictCount === 0 ? (
              <div className="success-callout" style={{ marginTop: "var(--space-4)" }}>
                No unresolved evidence conflicts across {report.total_findings} finding{report.total_findings === 1 ? "" : "s"}, {report.project_count} project{report.project_count === 1 ? "" : "s"}.
              </div>
            ) : (
              <div className="conflict-callout" style={{ marginTop: "var(--space-4)" }}>
                {conflictCount} finding{conflictCount === 1 ? "" : "s"} show conflicting evidence somewhere in this client's projects and need review.
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Projects in this client</h2>} />
          <CardBody>
            {report.projects.length === 0 ? (
              <p style={{ margin: 0, color: "var(--text-tertiary)", fontSize: "var(--font-size-sm)" }}>No projects yet.</p>
            ) : (
              <div className="table-wrapper">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Project</th>
                      <th>Status</th>
                      <th>Tasks delivered</th>
                      <th>Findings</th>
                      <th>Pending approvals</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.projects.map((p) => (
                      <tr key={p.project.id}>
                        <td>
                          <Link href={`/app/projects/${p.project.id}/reports`} style={{ fontWeight: "var(--font-weight-medium)", color: "var(--text-primary)" }}>
                            {p.project.name}
                          </Link>
                        </td>
                        <td>
                          <StatusBadge status={projectStatusDisplay(p.project.status)} />
                        </td>
                        <td>
                          {p.requirements_delivered} / {p.total_requirements} (
                          {formatPercent(p.total_requirements ? p.requirements_delivered / p.total_requirements : 0)})
                        </td>
                        <td>{p.total_findings}</td>
                        <td>{p.pending_approvals}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Findings by status</h2>} />
          <CardBody>
            {report.findings_by_status.length === 0 ? (
              <p style={{ margin: 0, color: "var(--text-tertiary)", fontSize: "var(--font-size-sm)" }}>No findings recorded yet.</p>
            ) : (
              <div style={{ display: "flex", flexWrap: "wrap", gap: "var(--space-3)" }}>
                {report.findings_by_status.map((s) => (
                  <div key={s.status} className="card" style={{ padding: "var(--space-3) var(--space-4)", minWidth: "9rem" }}>
                    <StatusBadge status={findingStatusDisplay(s.status)} />
                    <p style={{ margin: "var(--space-2) 0 0", fontSize: "var(--font-size-2xl)", fontWeight: "var(--font-weight-semibold)" }}>
                      {s.count}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Recent findings</h2>} />
          <CardBody>
            {report.recent_findings.length === 0 ? (
              <p style={{ margin: 0, color: "var(--text-tertiary)", fontSize: "var(--font-size-sm)" }}>No findings yet.</p>
            ) : (
              <div style={{ display: "grid", gap: "var(--space-3)" }}>
                {report.recent_findings.map(({ project, finding }) => (
                  <Link
                    key={finding.id}
                    href={`/app/projects/${project.id}/findings/${finding.id}`}
                    style={{ display: "block", paddingBottom: "var(--space-3)", borderBottom: "1px solid var(--border-subtle)", textDecoration: "none", color: "inherit" }}
                  >
                    <div style={{ display: "flex", justifyContent: "space-between", gap: "var(--space-3)" }}>
                      <p style={{ margin: 0, fontSize: "var(--font-size-sm)" }}>{finding.summary}</p>
                      <StatusBadge status={findingStatusDisplay(finding.status)} />
                    </div>
                    <p style={{ margin: "var(--space-1) 0 0", fontSize: "var(--font-size-xs)", color: "var(--text-tertiary)" }}>
                      {project.name} · {finding.citations.length} citation{finding.citations.length === 1 ? "" : "s"} · {formatPercent(finding.confidence)} confidence
                    </p>
                  </Link>
                ))}
              </div>
            )}
          </CardBody>
        </Card>
      </div>
    </div>
  );
}

function SummaryMetric({ label, value, warn }: { label: string; value: number | string; warn?: boolean }) {
  return (
    <div>
      <p style={{ margin: 0, fontSize: "var(--font-size-sm)", color: "var(--text-secondary)" }}>{label}</p>
      <p
        style={{
          margin: "var(--space-2) 0 0",
          fontSize: "var(--font-size-3xl)",
          fontWeight: "var(--font-weight-semibold)",
          color: warn ? "var(--color-warning-700)" : "var(--text-primary)",
        }}
      >
        {value}
      </p>
    </div>
  );
}
