"use client";

import { Printer } from "lucide-react";
import { useParams } from "next/navigation";

import { useProjectReport } from "@/hooks/useProjects";
import { formatDateTime, formatPercent } from "@/lib/format";
import { findingStatusDisplay, phaseStatusDisplay } from "@/lib/status";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { ErrorState } from "@/components/ui/ErrorState";
import { StatusBadge } from "@/components/ui/Badge";
import { SkeletonCard } from "@/components/ui/Skeleton";

export default function ReportPage() {
  const params = useParams<{ projectId: string }>();
  const { data: report, isLoading, error, refetch } = useProjectReport(params.projectId);

  if (error) return <ErrorState error={error} onRetry={() => refetch()} />;
  if (isLoading || !report) return <SkeletonCard />;

  const conflictCount = report.findings_by_status.find((s) => s.status === "CONFLICTING")?.count ?? 0;

  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "var(--space-4)", marginBottom: "var(--space-5)" }}>
        <div>
          <h1 style={{ margin: 0, fontSize: "var(--font-size-xl)", fontWeight: "var(--font-weight-semibold)" }}>
            {report.project.name} — Project Report
          </h1>
          <p style={{ margin: "var(--space-1) 0 0", fontSize: "var(--font-size-sm)", color: "var(--text-tertiary)" }}>
            Generated {formatDateTime(report.generated_at)} · Every figure below is computed directly from live
            project data, never generated by the AI.
          </p>
        </div>
        <Button variant="secondary" onClick={() => window.print()}>
          <Printer size={15} aria-hidden /> Export PDF
        </Button>
      </div>

      <div id="report-print-root" style={{ display: "grid", gap: "var(--space-5)" }}>
        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Executive summary</h2>} />
          <CardBody>
            <div className="metric-grid" style={{ gridTemplateColumns: "repeat(4, minmax(0,1fr))" }}>
              <SummaryMetric label="Evidence sources" value={report.total_sources} />
              <SummaryMetric label="Requirements tracked" value={report.total_requirements} />
              <SummaryMetric label="Findings" value={report.total_findings} />
              <SummaryMetric label="Conflicts found" value={conflictCount} warn={conflictCount > 0} />
            </div>
            {report.total_findings === 0 ? (
              <div className="uncertainty-callout" style={{ marginTop: "var(--space-4)" }}>
                No findings have been recorded yet — this project's scope hasn&rsquo;t been investigated, so there is
                nothing to confirm as conflict-free.
              </div>
            ) : conflictCount === 0 ? (
              <div className="success-callout" style={{ marginTop: "var(--space-4)" }}>
                No unresolved evidence conflicts were found across {report.total_findings} finding
                {report.total_findings === 1 ? "" : "s"}.
              </div>
            ) : (
              <div className="conflict-callout" style={{ marginTop: "var(--space-4)" }}>
                {conflictCount} finding{conflictCount === 1 ? "" : "s"} currently show conflicting evidence and need
                review before this project's status can be considered settled.
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Phase progress</h2>} />
          <CardBody>
            {report.phase_progress.length === 0 ? (
              <p style={{ margin: 0, color: "var(--text-tertiary)", fontSize: "var(--font-size-sm)" }}>No phases defined yet.</p>
            ) : (
              <div className="table-wrapper">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Phase</th>
                      <th>Status</th>
                      <th>Requirements</th>
                      <th>Delivered · verified</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.phase_progress.map((p) => (
                      <tr key={p.phase.id}>
                        <td>
                          Phase {p.phase.phase_number}: {p.phase.name}
                        </td>
                        <td>
                          <StatusBadge status={phaseStatusDisplay(p.phase.status)} />
                        </td>
                        <td>{p.requirement_count}</td>
                        <td>
                          {p.requirements_delivered} / {p.requirement_count} (
                          {formatPercent(p.requirement_count ? p.requirements_delivered / p.requirement_count : 0)})
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Findings by status</h2>} />
          <CardBody>
            {report.findings_by_status.length === 0 ? (
              <p style={{ margin: 0, color: "var(--text-tertiary)", fontSize: "var(--font-size-sm)" }}>No findings recorded yet.</p>
            ) : (
              <div style={{ display: "flex", flexWrap: "wrap", gap: "var(--space-3)" }}>
                {report.findings_by_status.map((s) => (
                  <div key={s.status} className="card" style={{ padding: "var(--space-3) var(--space-4)", minWidth: "9rem" }}>
                    <StatusBadge status={findingStatusDisplay(s.status)} />
                    <p style={{ margin: "var(--space-2) 0 0", fontSize: "var(--font-size-2xl)", fontWeight: "var(--font-weight-semibold)" }}>
                      {s.count}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Recent findings</h2>} />
          <CardBody>
            {report.recent_findings.length === 0 ? (
              <p style={{ margin: 0, color: "var(--text-tertiary)", fontSize: "var(--font-size-sm)" }}>No findings yet.</p>
            ) : (
              <div style={{ display: "grid", gap: "var(--space-3)" }}>
                {report.recent_findings.map((f) => (
                  <div key={f.id} style={{ paddingBottom: "var(--space-3)", borderBottom: "1px solid var(--border-subtle)" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", gap: "var(--space-3)" }}>
                      <p style={{ margin: 0, fontSize: "var(--font-size-sm)" }}>{f.summary}</p>
                      <StatusBadge status={findingStatusDisplay(f.status)} />
                    </div>
                    <p style={{ margin: "var(--space-1) 0 0", fontSize: "var(--font-size-xs)", color: "var(--text-tertiary)" }}>
                      {f.citations.length} citation{f.citations.length === 1 ? "" : "s"} · {formatPercent(f.confidence)} confidence
                    </p>
                  </div>
                ))}
              </div>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader title={<h2 style={{ margin: 0, fontSize: "var(--font-size-lg)", fontWeight: "var(--font-weight-semibold)" }}>Next steps</h2>} />
          <CardBody>
            <ul style={{ margin: 0, paddingLeft: "1.1rem", display: "grid", gap: "var(--space-2)", fontSize: "var(--font-size-sm)" }}>
              {report.pending_approvals > 0 && <li>{report.pending_approvals} action(s) are waiting for approval.</li>}
              {conflictCount > 0 && <li>Resolve {conflictCount} conflicting finding(s) before treating scope as settled.</li>}
              {report.total_sources === 0 && <li>Connect or upload evidence — no sources have been indexed yet.</li>}
              {report.total_sources > 0 && report.total_findings === 0 && (
                <li>Evidence is connected but no investigation has run yet — ask a scope question to generate findings.</li>
              )}
              {report.pending_approvals === 0 && conflictCount === 0 && report.total_findings > 0 && (
                <li>No outstanding actions — this project's evidence and findings are current.</li>
              )}
            </ul>
          </CardBody>
        </Card>
      </div>
    </div>
  );
}

function SummaryMetric({ label, value, warn }: { label: string; value: number; warn?: boolean }) {
  return (
    <div>
      <p style={{ margin: 0, fontSize: "var(--font-size-sm)", color: "var(--text-secondary)" }}>{label}</p>
      <p
        style={{
          margin: "var(--space-2) 0 0",
          fontSize: "var(--font-size-3xl)",
          fontWeight: "var(--font-weight-semibold)",
          color: warn ? "var(--color-warning-700)" : "var(--text-primary)",
        }}
      >
        {value}
      </p>
    </div>
  );
}
