"""add missing erd index plan indexes

Revision ID: 11019ce715b9
Revises: 19e79c0a5666
Create Date: 2026-09-12 19:55:56.128407
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11019ce715b9'
down_revision: Union[str, None] = '19e79c0a5666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_members_user_project', 'project_members', ['user_id', 'project_id'], unique=False)
    op.create_index('ix_projects_tenant_status', 'projects', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_source_records_connector_external', 'source_records', ['connector_id', 'external_id'], unique=False)
    op.create_index('ix_source_records_tenant_type', 'source_records', ['tenant_id', 'record_type'], unique=False)
    op.create_index('ix_source_versions_hash', 'source_versions', ['content_hash'], unique=False)
    op.create_index('ix_source_versions_record_modified', 'source_versions', ['source_record_id', sa.literal_column('modified_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_versions_record_modified', table_name='source_versions')
    op.drop_index('ix_source_versions_hash', table_name='source_versions')
    op.drop_index('ix_source_records_tenant_type', table_name='source_records')
    op.drop_index('ix_source_records_connector_external', table_name='source_records')
    op.drop_index('ix_projects_tenant_status', table_name='projects')
    op.drop_index('ix_project_members_user_project', table_name='project_members')
    # ### end Alembic commands ###
