"""source_records source_versions

Revision ID: 19e79c0a5666
Revises: 4d815fa2acdd
Create Date: 2026-09-12 19:52:13.670136
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19e79c0a5666'
down_revision: Union[str, None] = '4d815fa2acdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(length=30), server_default='PROJECT', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_source_records_connector_id_connectors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_source_records_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_source_records_connector_id_external_id')
    )
    op.create_table('source_versions',
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('version_key', sa.String(), nullable=False),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meeting_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_object_uri', sa.String(), nullable=True),
    sa.Column('extracted_text_uri', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_source_versions_source_record_id_source_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_versions')),
    sa.UniqueConstraint('source_record_id', 'version_key', name='uq_source_versions_source_record_id_version_key')
    )
    # source_records.current_version_id -> source_versions.id is added as a
    # separate ALTER TABLE, hand-edited in after autogenerate: the two
    # tables form a cycle (source_versions.source_record_id also points
    # back at source_records), so this FK cannot be inline in either
    # CREATE TABLE — source_versions doesn't exist yet while source_records
    # is being created. See atlasai_db.models.evidence for the ORM-side
    # `use_alter=True` that documents the same constraint.
    op.create_foreign_key(
        'fk_source_records_current_version_id_source_versions',
        'source_records', 'source_versions',
        ['current_version_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_source_records_current_version_id_source_versions', 'source_records', type_='foreignkey')
    op.drop_table('source_versions')
    op.drop_table('source_records')
    # ### end Alembic commands ###
