"""requirements task fields and comments

Revision ID: 49b0f7bd482e
Revises: be387e2b8fd0
Create Date: 2026-09-14 19:48:08.343589
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49b0f7bd482e'
down_revision: Union[str, None] = 'be387e2b8fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_comments',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_requirement_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_comments_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_comments'))
    )
    op.create_index('ix_requirement_comments_requirement_created', 'requirement_comments', ['requirement_id', 'created_at'], unique=False)
    # NOTE: autogenerate also proposed dropping+recreating
    # 'ix_evidence_chunks_embedding_hnsw' — a reflection artifact of how
    # Alembic compares pgvector HNSW index options, unrelated to this
    # migration's actual change. Deliberately not touching that index here.
    op.add_column('requirements', sa.Column('task_status', sa.String(length=20), server_default='TO_DO', nullable=False))
    op.add_column('requirements', sa.Column('priority', sa.String(length=20), server_default='NORMAL', nullable=False))
    op.add_column('requirements', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.create_index('ix_requirements_assignee', 'requirements', ['assignee_id'], unique=False)
    op.create_index('ix_requirements_project_priority', 'requirements', ['project_id', 'priority'], unique=False)
    op.create_index('ix_requirements_project_task_status', 'requirements', ['project_id', 'task_status'], unique=False)
    op.create_foreign_key(op.f('fk_requirements_assignee_id_users'), 'requirements', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_requirements_assignee_id_users'), 'requirements', type_='foreignkey')
    op.drop_index('ix_requirements_project_task_status', table_name='requirements')
    op.drop_index('ix_requirements_project_priority', table_name='requirements')
    op.drop_index('ix_requirements_assignee', table_name='requirements')
    op.drop_column('requirements', 'assignee_id')
    op.drop_column('requirements', 'priority')
    op.drop_column('requirements', 'task_status')
    op.drop_index('ix_requirement_comments_requirement_created', table_name='requirement_comments')
    op.drop_table('requirement_comments')
    # ### end Alembic commands ###
