"""connectors connector_scopes sync_runs

Revision ID: 4d815fa2acdd
Revises: c0cb543a8167
Create Date: 2026-09-12 19:52:04.235247
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4d815fa2acdd'
down_revision: Union[str, None] = 'c0cb543a8167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('credential_ref', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_connectors_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors'))
    )
    op.create_table('connector_scopes',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_external_id', sa.String(), nullable=True),
    sa.Column('scope_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_connector_scopes_connector_id_connectors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_connector_scopes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_scopes')),
    sa.UniqueConstraint('connector_id', 'project_id', 'scope_type', 'scope_external_id', name='uq_connector_scopes_identity')
    )
    op.create_table('sync_runs',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('cursor_before', sa.String(), nullable=True),
    sa.Column('cursor_after', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_changed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('finished_at is null or finished_at >= started_at', name=op.f('ck_sync_runs_finished_after_started')),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_sync_runs_connector_id_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs')
    op.drop_table('connector_scopes')
    op.drop_table('connectors')
    # ### end Alembic commands ###
