"""requirements requirement_evidence claims decisions delivery_records

Revision ID: 5767456757cd
Revises: ee0aa2d22dcc
Create Date: 2026-09-12 19:56:55.822544
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5767456757cd'
down_revision: Union[str, None] = 'ee0aa2d22dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('decision_text', sa.String(), nullable=False),
    sa.Column('decision_status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_decisions_approved_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_decisions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_table('requirements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], name=op.f('fk_requirements_phase_id_phases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requirements_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('project_id', 'key', name='uq_requirements_project_id_key')
    )
    op.create_index('ix_requirements_phase', 'requirements', ['phase_id'], unique=False)
    op.create_index('ix_requirements_project_status', 'requirements', ['project_id', 'status'], unique=False)
    op.create_table('delivery_records',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('evidence_summary', sa.String(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_delivery_records_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_delivery_records_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_delivery_records_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_delivery_records_verified_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_records'))
    )
    op.create_table('claims',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('evidence_chunk_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('polarity', sa.String(length=20), nullable=False),
    sa.Column('extracted_by', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence is null or confidence between 0 and 1', name=op.f('ck_claims_confidence_range')),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunks.id'], name=op.f('fk_claims_evidence_chunk_id_evidence_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_claims_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_table('requirement_evidence',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('evidence_chunk_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.CheckConstraint('confidence is null or confidence between 0 and 1', name=op.f('ck_requirement_evidence_confidence_range')),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunks.id'], name=op.f('fk_requirement_evidence_evidence_chunk_id_evidence_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_evidence_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_id', 'evidence_chunk_id', 'relation_type', name=op.f('pk_requirement_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_evidence')
    op.drop_table('claims')
    op.drop_table('delivery_records')
    op.drop_index('ix_requirements_project_status', table_name='requirements')
    op.drop_index('ix_requirements_phase', table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('decisions')
    # ### end Alembic commands ###
