"""findings finding_citations

Revision ID: 69426fb66a45
Revises: e5e118a367e6
Create Date: 2026-09-12 19:57:25.188458
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '69426fb66a45'
down_revision: Union[str, None] = 'e5e118a367e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('inferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence is null or confidence between 0 and 1', name=op.f('ck_findings_confidence_range')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_findings_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_findings_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index('ix_findings_project_created', 'findings', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('finding_citations',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evidence_chunk_id', sa.UUID(), nullable=False),
    sa.Column('citation_label', sa.String(length=50), nullable=True),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('location_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunks.id'], name=op.f('fk_finding_citations_evidence_chunk_id_evidence_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_citations_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'evidence_chunk_id', name=op.f('pk_finding_citations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_citations')
    op.drop_index('ix_findings_project_created', table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
