"""spaces and project space_id

Revision ID: 7a3f9c1d2b44
Revises: 49b0f7bd482e
Create Date: 2026-09-19 00:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a3f9c1d2b44'
down_revision: Union[str, None] = '49b0f7bd482e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_spaces_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_spaces_tenant_id_name')
    )
    op.create_index('ix_spaces_tenant_status', 'spaces', ['tenant_id', 'status'], unique=False)
    op.add_column('projects', sa.Column('space_id', sa.UUID(), nullable=True))
    op.create_index('ix_projects_space_status', 'projects', ['space_id', 'status'], unique=False)
    op.create_foreign_key(op.f('fk_projects_space_id_spaces'), 'projects', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_space_id_spaces'), 'projects', type_='foreignkey')
    op.drop_index('ix_projects_space_status', table_name='projects')
    op.drop_column('projects', 'space_id')
    op.drop_index('ix_spaces_tenant_status', table_name='spaces')
    op.drop_table('spaces')
    # ### end Alembic commands ###
