"""sprints and requirement sprint/due_date fields

Revision ID: c9d4e8f2a611
Revises: 7a3f9c1d2b44
Create Date: 2026-09-19 00:05:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9d4e8f2a611'
down_revision: Union[str, None] = '7a3f9c1d2b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sprint_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PLANNED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('end_date is null or start_date is null or end_date >= start_date', name=op.f('ck_sprints_end_date_after_start_date')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sprints_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprints')),
    sa.UniqueConstraint('project_id', 'sprint_number', name='uq_sprints_project_id_sprint_number')
    )
    op.add_column('requirements', sa.Column('sprint_id', sa.UUID(), nullable=True))
    op.add_column('requirements', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index('ix_requirements_sprint', 'requirements', ['sprint_id'], unique=False)
    op.create_index('ix_requirements_project_sprint', 'requirements', ['project_id', 'sprint_id'], unique=False)
    op.create_foreign_key(op.f('fk_requirements_sprint_id_sprints'), 'requirements', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_requirements_sprint_id_sprints'), 'requirements', type_='foreignkey')
    op.drop_index('ix_requirements_project_sprint', table_name='requirements')
    op.drop_index('ix_requirements_sprint', table_name='requirements')
    op.drop_column('requirements', 'due_date')
    op.drop_column('requirements', 'sprint_id')
    op.drop_table('sprints')
    # ### end Alembic commands ###
