"""evidence_chunks

Revision ID: ee0aa2d22dcc
Revises: 11019ce715b9
Create Date: 2026-09-12 19:56:07.500329
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = 'ee0aa2d22dcc'
down_revision: Union[str, None] = '11019ce715b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_chunks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('cell_range', sa.String(), nullable=True),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=True),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('embedding_model', sa.String(length=150), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_ms is null or end_ms is null or end_ms >= start_ms', name=op.f('ck_evidence_chunks_end_ms_after_start_ms')),
    sa.CheckConstraint('token_count is null or token_count >= 0', name=op.f('ck_evidence_chunks_token_count_nonnegative')),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], name=op.f('fk_evidence_chunks_source_version_id_source_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_evidence_chunks_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_chunks')),
    sa.UniqueConstraint('source_version_id', 'chunk_index', name='uq_evidence_chunks_source_version_id_chunk_index')
    )
    op.create_index('ix_evidence_chunks_search_tsv', 'evidence_chunks', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_evidence_chunks_tenant_version', 'evidence_chunks', ['tenant_id', 'source_version_id'], unique=False)
    # ### end Alembic commands ###

    # search_tsv is DB-managed, never written from Python (see
    # atlasai_db.models.evidence.EvidenceChunk.search_tsv docstring).
    # 'english' is hardcoded rather than driven by a per-row/per-tenant
    # setting because pgvector/evidence_chunks has no language column today;
    # revisit if/when AtlasAI supports non-English evidence corpora.
    op.execute(
        """
        CREATE FUNCTION evidence_chunks_tsv_update() RETURNS trigger AS $$
        BEGIN
          NEW.search_tsv := to_tsvector('english', coalesce(NEW.content, ''));
          RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER evidence_chunks_tsv_update_trigger
        BEFORE INSERT OR UPDATE OF content ON evidence_chunks
        FOR EACH ROW EXECUTE FUNCTION evidence_chunks_tsv_update();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS evidence_chunks_tsv_update_trigger ON evidence_chunks")
    op.execute("DROP FUNCTION IF EXISTS evidence_chunks_tsv_update()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_chunks_tenant_version', table_name='evidence_chunks')
    op.drop_index('ix_evidence_chunks_search_tsv', table_name='evidence_chunks', postgresql_using='gin')
    op.drop_table('evidence_chunks')
    # ### end Alembic commands ###
